### PR TITLE
zero out dask pools

### PR DESCRIPTION
**Pull request by athornton**

### CODE REVIEW

**Review by rra — COMMENTED** [review]
I know it's a hassle, but we never make a change to all environments at once in Terraform. Could you do dev and int first, and then once that's applied and we know nothing weird happens, we can do prod during our upgrade window?

**Comment by athornton** [comment]
Sure

**Review by rra — COMMENTED** [review]
Looks like Terraform is saying that you are not allowed to set that value to 0.

**Comment by athornton** [comment]
Well, that's annoying.  Fine.  Dump the pools entirely then.

**Review by rra — APPROVED** [review]

**Pull request merged**
