### PR TITLE
Roundtable Vault and LFS IAM Fixes

### PR DESCRIPTION
**Pull request by dspeck1**
Change from iam binding to iam member which is non authorative for vault and git lfs. Change casing to underscores to be consistent. Ran terraform fmt to adjust spacing. Adjust serial to run terraform plan.

### CODE REVIEW

**Comment by athornton** [comment]
I like it, but I'm going to check it out and remove the service accounts variable.

**Comment by athornton** [comment]
LGTM, but I'd like you to check my work too, please.

**Review by athornton — APPROVED** [review]
LGTM, but please check the stuff I added.

**Comment by dspeck1** [comment]
LGTM

**Pull request merged**
