### PR TITLE
Add Alert Production subfolders

### PR DESCRIPTION
**Pull request by spenczar**
Depends upon #317.

### CODE REVIEW

**Review by hsinfang — APPROVED** [review]
LGTM.  

The DM policy is to rebase on the new master. You seem to have merged master into the branch?

**Comment by spenczar** [comment]
Thanks for the review.

Yeah, sorry about the merge; old habits die hard I guess.

Fortunately, it doesn't make any difference here, since the merge was perfectly fast-forwardable, so the merge commit is empty. It has [no diffs](https://github.com/lsst/idf_deploy/commit/cb1f29b66d327df5476babde1579e0b4638e1b80), and is pure metadata. A rebase would have worked too, but would require force-pushing and breaking public history - but yeah, I get that that's the DM way.

**Comment by ktlim** [comment]
Ticket branches, and even more so `u/` branches, while publicly visible, are not supposed to be used by multiple users and so are safe to "break history".

**Comment by ktlim** [comment]
See the difference between previous merges and this one:
Screen Shot 2021-08-18 at 1 06 14 PM

**Comment by spenczar** [comment]
Right, the metadata of the merge commit is still present. I just don't see how it could ever make a difference; `git bisect` will always do the right thing, as will `git blame`, and `git log <some file>`, and so on. But anyway! This is probably not the place for debating the policy :)

**Pull request merged**
