### PR TITLE
DM-39014: Add dedicated Kafka and Zookeeper node pools in Roundtable

### PR DESCRIPTION
**Pull request by jonathansick**
These node pools include taints to ensure that only Kafka or Zookeeper processes run on these nodes.

### CODE REVIEW

**Comment by jonathansick** [comment]
@dspeck1 One thing I'm not sure of is the Kubernetes labels that get applied to the node pools. I don't think the labels I'm setting in `*-gka.tfvars` (i.e. `kafka = ok`) is being applied. Now, it's not crucial because the taints are really what I need, but I'm a bit puzzeled about the `node_polls_labels` variable and how it works.

**Comment by dspeck1** [comment]
Update [here](https://github.com/lsst/idf_deploy/blob/3fd8985838d88ee042d4415b2ddcba8424ec8a2f/environment/deployments/roundtable/gke/main.tf#L58) to add kafka label first then send in value via tfvars.

**Comment by jonathansick** [comment]
@dspeck1 Thanks. I guess I don't know the `infrastucture = ok` label is supposed to work from the RSP node pools (I don't see those labels, so I suspect they aren't working).

It turns out I don't really need these labels after all, since it's only the taint that's important for this application.

I've dropped the label changes; would you mind reviewing?

**Review by dspeck1 — APPROVED** [review]
looks good

**Pull request merged**
